name 'olyn_warmer'
maintainer 'Scott Richardson'
maintainer_email 'dev@grogwood.com'
chef_version '~> 16'
license 'GPL-3.0'
supports 'debian', '>= 10'
source_url 'https://gitlab.com/olyn/olyn_warmer'
description 'Parses sitemap URLs to warm them in a cache such as Varnish'
version '1.1.0'

provides 'olyn_warmer::default'
provides 'olyn_warmer::nokogiri'
provides 'olyn_warmer::sitemaps'
provides 'olyn_warmer::urls'
recipe 'olyn_warmer::default', 'Parses sitemaps and warms URLs'
recipe 'olyn_warmer::nokogiri', 'Installs nokogiri gem'
recipe 'olyn_warmer::sitemaps', 'Parses sitemaps from a data bag for all URLs'
recipe 'olyn_warmer::urls', 'Warms the URLs found in sitemaps'

gem 'nokogiri'
